spring:
  thymeleaf:
    cache: false

logging:
  level:
#    com:
#      iglucose:
#        portal:
#          api:
#            resource:
#              PerformanceReportsResource: DEBUG
    com:
      iglucose:
        portal:
          service:
            impl:
              PerformanceReportsServiceImpl: DEBUG
#              ChartConfigBuilderServiceImpl: DEBUG
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#        http: DEBUG
#        jdbc:
#          core: TRACE
